### ISSUE TITLE
Crash on quitting the app in JavaScriptInOrderExecutor

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/libquentier#190]
Reproduces sometimes on quitting the app. Stack trace from master branch:
```
Thread 1 "quentier" received signal SIGSEGV, Segmentation fault.
0x00007ff8bbc4b270 in std::__atomic_base<QThreadData*>::load (__m=std::memory_order_acquire, this=0x69) at /usr/include/c++/9/bits/atomic_base.h:734
734           load(memory_order __m = memory_order_seq_cst) const noexcept
(gdb) bt
#0  0x00007ff8bbc4b270 in std::__atomic_base<QThreadData*>::load(std::memory_order) const (__m=std::memory_order_acquire, this=0x69)
    at /usr/include/c++/9/bits/atomic_base.h:734
#1  std::atomic<QThreadData*>::load(std::memory_order) const (__m=std::memory_order_acquire, this=0x69) at /usr/include/c++/9/atomic:519
#2  QAtomicOps<QThreadData*>::loadAcquire<QThreadData*>(std::atomic<QThreadData*> const&) (_q_value=...)
    at ../../include/QtCore/../../src/corelib/thread/qatomic_cxx11.h:251
#3  QBasicAtomicPointer<QThreadData>::loadAcquire() const (this=0x69) at ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:255
#4  QBasicAtomicPointer<QThreadData>::operator QThreadData*() const (this=0x69) at ../../include/QtCore/../../src/corelib/thread/qbasicatomic.h:251
#5  QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*)
    (sender=0x5c1a180, signal_index=19, receiver=0x606d770, slot=<optimized out>, slotObj=0x5fc6a10, type=Qt::AutoConnection, types=0x0, senderMetaObject=0x7ff8c62f0c60 <QWebEnginePage::staticMetaObject>) at kernel/qobject.cpp:5053
#6  0x00007ff8bbc4b765 in QObject::connectImpl(QObject const*, void**, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*)
    (sender=0x5c1a180, signal=<optimized out>, receiver=0x606d770, slot=0x7fff1f1deca0, slotObj=0x5fc6a10, type=Qt::AutoConnection, types=0x0, senderMetaObject=<optimized out>) at kernel/qobject.cpp:5001
#7  0x00007ff8c62dca1f in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#8  0x00007ff8c62cd1ee in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#9  0x00007ff8c62dd3c6 in QWebEngineView::page() const () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#10 0x00007ff8c70e9e3b in quentier::JavaScriptInOrderExecutor::start() (this=0x63878b0)
    at /home/dmitry/workspace/MyOpenSourceProjects/libquentier-master/src/note_editor/JavaScriptInOrderExecutor.cpp:58
#11 0x00007ff8c70ea3ae in quentier::JavaScriptInOrderExecutor::next(QVariant const&) (this=0x63878b0, data=<invalid type>)
    at /home/dmitry/workspace/MyOpenSourceProjects/libquentier-master/src/note_editor/JavaScriptInOrderExecutor.cpp:85
#12 0x00007ff8c70ea57d in quentier::JavaScriptInOrderExecutor::JavaScriptCallback::operator()(QVariant const&) (this=0x610b970, result=<invalid type>)
    at /home/dmitry/workspace/MyOpenSourceProjects/libquentier-master/src/note_editor/JavaScriptInOrderExecutor.cpp:92
#13 0x00007ff8c70ebb06 in QtWebEnginePrivate::QWebEngineCallbackPrivate<QVariant const&, quentier::JavaScriptInOrderExecutor::JavaScriptCallback>::operator()(QVariant const&) (this=0x610b960, value=<invalid type>) at /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore/qwebenginecallback.h:69
#14 0x00007ff8c62d55fe in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#15 0x00007ff8c62d4cce in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#16 0x00007ff8c62d4e1d in  () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#17 0x00007ff8c62cfc67 in QWebEnginePage::~QWebEnginePage() () at /usr/lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#18 0x00007ff8c6feb2b0 in quentier::NoteEditorPage::~NoteEditorPage() (this=0x6387820)
    at /home/dmitry/workspace/MyOpenSourceProjects/libquentier-master/src/note_editor/NoteEditorPage.cpp:51
#19 0x00007ff8c6feb36c in quentier::NoteEditorPage::~NoteEditorPage() (this=0x6387820)
    at /home/dmitry/workspace/MyOpenSourceProjects/libquentier-master/src/note_editor/NoteEditorPage.cpp:49
#20 0x00007ff8bbc493ce in QObjectPrivate::deleteChildren() (this=this@entry=0x5ff8780) at kernel/qobject.cpp:2104
#21 0x00007ff8c5d276a6 in QWidget::~QWidget() (this=0x56afbe0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1522
```
It appears that there was an attempt to execute some JavaScript code in QWebEnginePage which was being destroyed at the moment, hence the crash.
Need to find some way to avoid it - for example, emit synchronous signal from NoteEditorPage's destructor that the page is about to destroy, to which NoteEditorPrivate would subscribe and set some flag for JavaScriptInOrderExecutor which would prevent the attempt to execute the next script.

**Comment by d1vanov** [comment]
Fixed in both master and development braches.
